--- #YAML:1.0
name: ExtUtils-ModuleMaker-TT
version: 0.72
author:
  - David A. Golden <david@dagolden.com>
abstract: |-
  Makes skeleton modules with Template Toolkit templates
license: perl
requires:
  Config::General: 2.19
  Cwd: 2.12
  Data::Dumper: 2.121
  ExtUtils::ModuleMaker: 0.32
  File::Basename: 0
  File::Path: 1.06
  File::Spec::Functions: 1.3
  Getopt::Long: 2.34
  Pod::Usage: 1
  Template: 2.13
build_requires:
  Module::Build: 0.24
  Test::Distribution: 1.11
provides:
  ExtUtils::ModuleMaker::TT:
    file: lib/ExtUtils/ModuleMaker/TT.pm
    version: 0.72
generated_by: Module::Build version 0.24
