---
name: ExtUtils-ModuleMaker-TT
version: 0.79
author:
  - David A Golden <dagolden@cpan.org>
abstract: Makes skeleton modules with Template Toolkit templates
license: perl
requires:
  Config::General: 2.19
  Cwd: 2.12
  Data::Dumper: 2.121
  ExtUtils::ModuleMaker: 0.39
  File::Basename: 0
  File::Path: 1.06
  File::Spec: 0.87
  File::Spec::Functions: 1.3
  File::Temp: 0.16
  Getopt::Long: 0
  Pod::Usage: 1
  Template: 2.13
  Test::More: 0.47
provides:
  ExtUtils::ModuleMaker::TT:
    file: lib/ExtUtils/ModuleMaker/TT.pm
    version: 0.79
generated_by: Module::Build version 0.2702
